routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DashboardController as adminDashboard;
use App\Http\Controllers\Admin\MedicineController as adminMed;
use App\Http\Controllers\Admin\MedicineTypeController as adminTypeMed;
use App\Http\Controllers\Admin\RecapController as adminRecapMed;
use App\Http\Controllers\Admin\IngoingController as adminObatMasuk;
use App\Http\Controllers\Admin\MedicineDataController as adminDataObat;
use App\Http\Controllers\Admin\OutgoingController as adminObatKeluar;
use App\Http\Controllers\Admin\ForecastingController as adminPeramalan;

use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => ['role:admin']], function () {
        //Dashboard
        Route::get('/dashboard', [adminDashboard::class, 'index'])->name('admin.dashboard');
        Route::post('ajax/getDataChart', [adminDashboard::class, 'getDataChart'])->name('admin.getDataChart');
        Route::get('ajax/getDataTahun', [adminDashboard::class, 'getDataTahun'])->name('admin.getTahun');
        Route::get('ajax/getDataObat', [adminDashboard::class, 'getDataObat'])->name('admin.getObat');
        Route::get('ajax/getDataLabel', [adminDashboard::class, 'getDataLabel'])->name('admin.getLabel');
        // Obat
        Route::resource('obat', adminMed::class);
        Route::get('obat/tambahStock/{id}', [adminMed::class, 'tambahStock'])->name('admin.obat.tambahStock');
        // Type
        Route::resource('tipe', adminTypeMed::class);
        // Recap
        Route::resource('rekap', adminRecapMed::class);
        Route::get('ajax/rekap/getTransaction', [adminRecapMed::class, 'getData'])->name('admin.rekap.getData');
        // Permintaan Transaction
        Route::resource('ingoing', adminObatMasuk::class);
        Route::resource('dataObat', adminDataObat::class);
        Route::get('ingoing/{id}/tipe', [adminObatMasuk::class, 'getType'])->name('ingoing.getType');
        // Obat Keluar Transaction
        Route::resource('outgoing', adminObatKeluar::class);
        Route::get('outgoing/{id}/tipe', [adminObatKeluar::class, 'getType'])->name('outgoing.getType');
        Route::get('ajax/outgoing/obat_all', [adminObatKeluar::class, 'getObat'])->name('outgoing.getObat');
        Route::get('ajax/outgoing/keranjang_all', [adminObatKeluar::class, 'getKeranjang'])->name('outgoing.getKeranjang');
        Route::get('ajax/outgoing/detail/{id}', [adminObatKeluar::class, 'getDetailTransaction'])->name('outgoing.getDetailInfo');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/addCart', [adminObatKeluar::class, 'addCart'])->name('outgoing.addCart');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/deleteItem', [adminObatKeluar::class, 'deleteItem'])->name('outgoing.deleteCartItem');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/updateItem', [adminObatKeluar::class, 'updateItem'])->name('outgoing.updateCartItem');
        // Forecasting
        Route::get('/forecasting', [adminPeramalan::class, 'index'])->name('admin.forecasting');
        Route::get('ajax/forecasting/getDataTahun/', [adminPeramalan::class, 'getDataTahun'])->name('admin.forecasting.getDataTahun');
        Route::get('ajax/forecasting/getDataBulan/', [adminPeramalan::class, 'getDataBulan'])->name('admin.forecasting.getDataBulan');
        Route::get('ajax/forecasting/getDataObat/', [adminPeramalan::class, 'getDataObat'])->name('admin.forecasting.getDataObat');
        Route::post('ajax/forecasting/calcultaeForecasting/', [adminPeramalan::class, 'calcultaeForecasting'])->name('admin.forecasting.calculateForecasting');
    });
});

Route::get('/landing', [HomeController::class, 'index'])->name('landing');

app/Http/Controllers/Admin/MedicineTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\MedicineType;
use Illuminate\Http\Request;

class MedicineTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $type = MedicineType::all();
        return view('admin.medicine_type.index', [
            'title' => 'tipe obat',
            'subtitle' => '',
            'active' => 'obat',
            'tipe' => $type
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.medicine_type.create', [
            'title' => 'tipe',
            'subtitle' => 'create',
            'active' => 'obat',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $target = MedicineType::where([
            ['name', $request->name],
        ])->first();

        if ($target) {
            return redirect()->back()->with('error_msg', 'Data Tipe Obat ' . $request->name . ' Sudah tersedia');
        }

        $request->validate([
            'name' => 'required|regex:/^[a-zA-Z ]+$/|unique:medicine_types,name'
        ], [
            'name.unique' => 'Tipe Obat sudah ditambahkan',
            'name.regex' => 'Tipe Obat harus huruf',
            'name.required' => 'Tipe Obat harap diisi'
        ]);
        
        $data = MedicineType::create([
            'name' => ucfirst($request->name)
        ]);

        return redirect()->route('obat.index')->with('success_msg', 'Tipe Obat ' . $data->name . ' berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = MedicineType::findOrFail($id);
        return view('admin.medicine_type.show', [
            'title' => 'tipe obat',
            'subtitle' => 'show',
            'active' => 'obat',
            'tipe' => $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = MedicineType::findOrFail($id);
        return view('admin.medicine_type.edit', [
            'title' => 'tipe',
            'subtitle' => 'edit',
            'active' => 'obat',
            'tipe' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|regex:/^[a-zA-Z ]+$/|unique:medicine_types,name,' . $id
        ], [
            'name.unique' => 'Tipe Obat '.$request->name.' sudah ditambahkan',
            'name.regex' => 'Tipe Obat harus huruf',
            'name.required' => 'Tipe Obat harap diisi'
        ]);

        MedicineType::where('id', $id)
            ->update(['name' => $request->name]);

        return redirect()->route('tipe.index')->with('success_msg', 'Tipe Obat ' . $request->name . ' berhasil diperbaruhi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $target = MedicineType::where('id', $id);
        $target->delete();
        return response()->json([
            'message' => 'Tipe Obat berhasil dihapus!'
        ]);
    }
}

resources/views/admin/medicine_type/create.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>{{ucfirst($title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('obat.index') }}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('tipe.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>name</label>
                        <input name="name" type="text" class="form-control @error('name') is-invalid @enderror"
                            value="{{ old('name') }}" autocomplete="name" autofocus>
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <input type="submit" class="btn btn-primary float-right" value="Tambah">
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/medicine_type/edit.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Ubah {{ucfirst($title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('tipe.index') }}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('tipe.update', $tipe->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('put') }}
                    <div class="form-group">
                        <label>name</label>
                        <input name="name" type="text" class="form-control @error('name') is-invalid @enderror"
                            value="{{ $tipe->name }}" autocomplete="name" autofocus>
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <input type="submit" class="btn btn-primary float-right" value="Ubah Data">
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/medicine_type/index.blade.php
@extends('layouts.myview')
@section('content')
{{-- <div class="row">
    <div class="col-md-6 col-md-12">
        <div class="card">
            <div class="card-header">
                <h4>Data Obat</h4>
            </div>
            <div class="card-body">
                <canvas id="chartharga"></canvas>
            </div>
        </div>
    </div>
</div> --}}
<div class="row">
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-header">
                <h4>Daftar Tipe Obat</h4>
                <div class="card-header-action">
                    <a href="{{ route('tipe.create') }}" class="btn btn-primary">Tambah </a>
                    <a href="{{ route('obat.index') }}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tipe" class="table table-striped">
                        <thead>
                            <th>{{__('No')}}</th>
                            <th>{{__('Nama')}}</th>
                            <th>{{__('Aksi')}}</th>
                        </thead>
                        <tbody>
                            <?php $no=1 ?>
                            @foreach ($tipe as $t)
                            <tr>
                                <td>{{$no}}</td>
                                <td>{{$t->name}}</td>
                                <td>
                                    <a href="{{ route('tipe.edit', $t->id) }}" class="btn btn-sm btn-icon icon-left btn-primary"><i class="far fa-edit"></i> Ubah</a>
                                    <a href="{{ route('tipe.destroy', $t->id) }}"
                                        class="btn btn-sm btn-danger hapus-tipe" data-toggle="tooltip" data-placement="top"
                                        title="Hapus Data" data-id="{{ $t->id }}">
                                        <i class="fa fa-trash"></i> Hapus
                                    </a>
                                </td>
                                <?php $no++ ?>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(document).ready(function() {
        $('#tipe').DataTable();
    });

    $('.hapus-tipe').on('click', function (e) {
        e.preventDefault();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var id = $(this).data("id");
        // var url = $('.hapus').attr('href');
        var url = "{{ route('tipe.destroy', ":id") }}";
        url = url.replace(':id', id);
        $object=$(this);

        Swal.fire({
            title: 'Are you sure?',
            text: "Yakin ingin menghapus Tipe Obat ini!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    data: {id: id},
                    success: function (response) {
                        $($object).parents('tr').remove();
                        Swal.fire({
                            title: "Data Dihapus!",
                            text: response.message,
                            icon: 'success',
                        });
                        location.reload();
                    },
                    error: function (data) {
                        Swal.fire({
                            title: "Data Gagal Dihapus!",
                            icon: 'error',
                        })
                    }
                });
            }
        });
    })
</script>
@endpush
{{-- @include('import.chartjs') --}}
@include('import.datatable')
{{-- var ctx2 = document.getElementById("chartpermintaan").getContext('2d');
        var myChart = new Chart(ctx2, {
            type: 'bar',
            data: {
                labels: @json($label),
                datasets: [
                    @foreach ($chart as $c)
                    {
                        label: @json(ucfirst($c['kecamatan'])) ,
                        data: @json($c['permintaan']),
                        borderColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                        backgroundColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                        pointRadius: 4
                    },
                    @endforeach
                ]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: @json(ucfirst($title)),
                    }
                },
                legend: {
                    display: true
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    x: {
                        stacked: true,
                    },
                    y: {
                        stacked: true
                    }
                },
            },
        }); --}}

        {{-- $(document).ready(function() {
            var ctx1 = document.getElementById("chartharga").getContext('2d');
            var myChart = new Chart(ctx1, {
                type: 'bar',
                data: {
                    labels: @json($label),
                    datasets: [
                        @foreach ($chart as $c)
                        {
                            label: @json(ucfirst($c['kecamatan'])) ,
                            data: @json($c['harga']),
                            borderColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                            backgroundColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                            pointRadius: 4
                        },
                        @endforeach
                    ]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: @json(ucfirst($title)),
                        }
                    },
                    legend: {
                        display: true
                    },
                    interaction: {
                        intersect: false,
                        mode: 'index',
                    },
                    scales: {
                        x: {
                            stacked: true,
                        },
                        y: {
                            stacked: true
                        }
                    },
                },
            });
    
    
        }); --}}