routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DashboardController as adminDashboard;
use App\Http\Controllers\Admin\MedicineController as adminMed;
use App\Http\Controllers\Admin\MedicineTypeController as adminTypeMed;
use App\Http\Controllers\Admin\RecapController as adminRecapMed;
use App\Http\Controllers\Admin\IngoingController as adminObatMasuk;
use App\Http\Controllers\Admin\MedicineDataController as adminDataObat;
use App\Http\Controllers\Admin\OutgoingController as adminObatKeluar;
use App\Http\Controllers\Admin\ForecastingController as adminPeramalan;

use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => ['role:admin']], function () {
        //Dashboard
        Route::get('/dashboard', [adminDashboard::class, 'index'])->name('admin.dashboard');
        Route::post('ajax/getDataChart', [adminDashboard::class, 'getDataChart'])->name('admin.getDataChart');
        Route::get('ajax/getDataTahun', [adminDashboard::class, 'getDataTahun'])->name('admin.getTahun');
        Route::get('ajax/getDataObat', [adminDashboard::class, 'getDataObat'])->name('admin.getObat');
        Route::get('ajax/getDataLabel', [adminDashboard::class, 'getDataLabel'])->name('admin.getLabel');
        // Obat
        Route::resource('obat', adminMed::class);
        Route::get('obat/tambahStock/{id}', [adminMed::class, 'tambahStock'])->name('admin.obat.tambahStock');
        // Type
        Route::resource('tipe', adminTypeMed::class);
        // Recap
        Route::resource('rekap', adminRecapMed::class);
        Route::get('ajax/rekap/getTransaction', [adminRecapMed::class, 'getData'])->name('admin.rekap.getData');
        // Permintaan Transaction
        Route::resource('ingoing', adminObatMasuk::class);
        Route::resource('dataObat', adminDataObat::class);
        Route::get('ingoing/{id}/tipe', [adminObatMasuk::class, 'getType'])->name('ingoing.getType');
        // Obat Keluar Transaction
        Route::resource('outgoing', adminObatKeluar::class);
        Route::get('outgoing/{id}/tipe', [adminObatKeluar::class, 'getType'])->name('outgoing.getType');
        Route::get('ajax/outgoing/obat_all', [adminObatKeluar::class, 'getObat'])->name('outgoing.getObat');
        Route::get('ajax/outgoing/keranjang_all', [adminObatKeluar::class, 'getKeranjang'])->name('outgoing.getKeranjang');
        Route::get('ajax/outgoing/detail/{id}', [adminObatKeluar::class, 'getDetailTransaction'])->name('outgoing.getDetailInfo');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/addCart', [adminObatKeluar::class, 'addCart'])->name('outgoing.addCart');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/deleteItem', [adminObatKeluar::class, 'deleteItem'])->name('outgoing.deleteCartItem');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/updateItem', [adminObatKeluar::class, 'updateItem'])->name('outgoing.updateCartItem');
        // Forecasting
        Route::get('/forecasting', [adminPeramalan::class, 'index'])->name('admin.forecasting');
        Route::get('ajax/forecasting/getDataTahun/', [adminPeramalan::class, 'getDataTahun'])->name('admin.forecasting.getDataTahun');
        Route::get('ajax/forecasting/getDataBulan/', [adminPeramalan::class, 'getDataBulan'])->name('admin.forecasting.getDataBulan');
        Route::get('ajax/forecasting/getDataObat/', [adminPeramalan::class, 'getDataObat'])->name('admin.forecasting.getDataObat');
        Route::post('ajax/forecasting/calcultaeForecasting/', [adminPeramalan::class, 'calcultaeForecasting'])->name('admin.forecasting.calculateForecasting');
    });
});

Route::get('/landing', [HomeController::class, 'index'])->name('landing');

app/Models/Medicine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicine extends Model
{
    use HasFactory;

    protected $table = 'medicines';
    protected $primaryKey = 'id';

    protected $fillable = [
        'name',
        'weight',
        'stock',
        'type_id'
    ];

    // protected $dates = ['expired_date'];
    protected $with = ['tipe'];

    /**
     * Get all of the tipe for the Medicine
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tipe()
    {
        return $this->belongsTo(MedicineType::class, 'type_id');
    }

    /**
     * Get all of the detail for the Medicine
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function detail()
    {
        return $this->hasMany(MedicineDetail::class, 'medicine_id');
    }

    /**
     * Get all of the order_detail for the Medicine
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function order_detail()
    {
        return $this->hasMany(TransactionDetail::class, 'medicine_id');
    }


}

app/Models/MedicineType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MedicineType extends Model
{
    use HasFactory;
    
    protected $table = 'medicine_types';
    protected $primaryKey = 'id';

    protected $fillable = [
        'name'
    ];

    // protected $with = ['obat'];

    public function obat()
    {
        return $this->hasOne(Medicine::class, 'type_id');
    }
}

app/Http/Controllers/Admin/MedicineController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Medicine;
use App\Models\MedicineDetail;
use App\Models\MedicineType;
use DateTime;
use Illuminate\Http\Request;

class MedicineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $type = MedicineType::all();
        $obat = Medicine::with(['tipe'])->get();
        return view('admin.medicine.index', [
            'title' => 'obat',
            'subtitle' => '',
            'active' => 'obat',
            'tipe' => $type,
            'obat' => $obat
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type = MedicineType::all();

        if (count($type) == 0) {
            return redirect()->route('obat.index')->with('error_msg', 'Silakan menambahkan Tipe obat sebelum menambahkan obat');
        }

        return view('admin.medicine.create', [
            'title' => 'obat',
            'subtitle' => 'create',
            'active' => 'obat',
            'tipe' => $type
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $target = Medicine::where([
            ['name', $request->name],
            ['type_id', $request->tipe]
        ])->with('tipe')->first();

        if ($target) {
            return redirect()->back()->with('error_msg', 'Data Obat ' . $request->name . ' dengan tipe ' . $target->tipe->name . ' Sudah tersedia');
        }

        $request->validate([
            'name' => 'required|regex:/^[a-zA-Z ]+$/',
            'tipe' => 'required',
            'mg' => 'nullable|numeric',
            'ml' => 'nullable|numeric',
            // 'expired_date' => 'required|date'
        ], [
            // 'name.unique' => 'Obat sudah ditambahkan',
            'name.regex' => 'Obat harus huruf',
            'name.required' => 'Obat harap diisi',
            'tipe.required' => 'Tipe harus diisi',
            'mg.numeric' => 'satuan miligram harus angka',
            'ml.numeric' => 'satuan mililiter harus angka',
        ]);

        if ($request->mg != null && $request->ml == null) {
            $weight = $request->mg;
        } elseif ($request->mg == null && $request->ml != null) {
            $weight = $request->ml;
        } else {
            $weight = $request->mg.'/'.$request->ml;
        }

        $date = new DateTime($request->expired_date);
        // dd();

        $data = Medicine::create([
            'name' => ucfirst($request->name),
            'type_id' => $request->tipe,
            'weight' => $weight, 
            // 'expired_date' => $date->format('Y-m-d H:i:s')
        ]);

        return redirect()->route('obat.index')->with('success_msg', 'Obat ' . $data->name . ' ' . $weight .' berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $data = Medicine::findOrFail($id);
        $data = MedicineDetail::where('medicine_id', $id)
                    ->orderBy('created_at', 'desc')
                    ->get();
        // dd($data);
        return view('admin.medicine.show', [
            'title' => 'obat',
            'subtitle' => 'show',
            'active' => 'obat',
            'data' => $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $obat = Medicine::findOrFail($id);
        $type = MedicineType::all();
        return view('admin.medicine.edit', [
            'title' => 'tipe',
            'subtitle' => 'edit',
            'active' => 'obat',
            'tipe' => $type,
            'obat' => $obat
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|regex:/^[a-zA-Z ]+$/|unique:medicines,name',
            'tipe' => 'required',
            'mg' => 'nullable|numeric',
            'ml' => 'nullable|numeric',
            // 'expired_date' => 'required|date'
        ], [
            'name.unique' => 'Obat sudah ditambahkan',
            'name.regex' => 'Obat harus huruf',
            'name.required' => 'Obat harap diisi',
            'tipe.required' => 'Tipe harus diisi',
            'mg.numeric' => 'satuan miligram harus angka',
            'ml.numeric' => 'satuan mililiter harus angka',
            // 'expired_date.required' => 'tanggal expired harus diisi',
            // 'expired_date.date' => 'tanggal expired harus format tanggal',
        ]);

        if ($request->mg != null && $request->ml == null) {
            $weight = $request->mg;
        } elseif ($request->mg == null && $request->ml != null) {
            $weight = $request->ml;
        } elseif ($request->mg != null && $request->ml != null) {
            $weight = $request->mg.'/'.$request->ml;
        } else {
            $weight = null;
        }

        $date = new DateTime($request->expired_date);

        Medicine::where('id', $id)
            ->update([
                'name' => ucfirst($request->name),
                'type_id' => $request->tipe,
                'weight' => $weight, 
                // 'expired_date' => $date->format('Y-m-d H:i:s')
            ]);

        return redirect()->route('obat.index')->with('success_msg', 'Obat ' . $request->name . ' berhasil diperbaruhi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $target = Medicine::where('id', $id);
        $target->delete();
        return response()->json([
            'message' => 'Obat berhasil dihapus!'
        ]);
    }

    public function tambahStock($id)
    {
        $data = MedicineDetail::where('id', $id)->first();
        // dd('masuk', $data);
        $data->update([
            'status' => 0
        ]);
        $obat = Medicine::where('id', $data->medicine_id)->first();
        $obat->update([
            'stock' => $obat->stock + $data->quantity
        ]);
        return redirect()->route('obat.index')->with('success_msg', 'Stock Obat ' . $obat->name . ' berhasil ditambah');
    }
}

resources/views/admin/medicine/create.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>{{ucfirst($title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('obat.index') }}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('obat.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>{{__('Tipe Obat')}}</label>
                        <select name="tipe" id="tipe" class="form-control @error('tipe') is-invalid @enderror">
                            @foreach ($tipe as $t)
                                <option value="{{$t->id}}">{{$t->name}}</option>
                            @endforeach
                        </select>
                        @error('tipe')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>{{__('Nama')}}</label>
                        <input name="name" type="text" class="form-control @error('name') is-invalid @enderror"
                            value="{{ old('name') }}" autocomplete="name" autofocus>
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>{{__('Satuan')}}</label>
                        <div class="row">
                            <div class="col-md-6 col-sm-12 mt-2">
                                <div class="form-group">
                                <div class="input-group">
                                    <input name="mg" type="text" class="form-control @error('mg') is-invalid @enderror"
                                        value="{{ old('mg') }}" autocomplete="mg" autofocus>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            mg
                                        </div>
                                    </div>
                                </div>
                                @error('mg')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 mt-2">
                                <div class="form-group">
                                <div class="input-group">
                                    <input name="ml" type="text" class="form-control @error('ml') is-invalid @enderror"
                                        value="{{ old('ml') }}" autocomplete="ml" autofocus>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            ml
                                        </div>
                                    </div>
                                </div>
                                @error('ml')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                                </div>
                            </div>    
                        </div>
                    </div>
                    {{-- <div class="form-group">
                        <label>{{__('Expired Date')}}</label>
                        <input name="expired_date" type="text" id="exp-date" class="form-control @error('expired_date') is-invalid @enderror"
                            value="{{ old('expired_date') }}" autocomplete="expired_date" data-date-format='dd-mm-yyyy' autofocus>
                        @error('expired_date')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div> --}}
                    <input type="submit" class="btn btn-primary float-right" value="Tambah">
                </form>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    var dateToday = new Date();

    $(document).ready(function(){
        // $("#exp-date").datepicker({
        //     autoclose: true,
        //     // minViewMode: 1,
        //     // language: 'id',
        //     // format: 'MM',
        //     startDate: dateToday,
        //     onSelect: function(selectedDate) {
        //         $('#exp-date').text();
        //     }
        // });
        $("#tipe").select2({
            placeholder: "Pilih Tipe Obat",
            allowClear: true
        });
    })
</script>
@endpush
@endsection

@include('import.select2')
@include('import.datepicker')

resources/views/admin/medicine/index.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    @include('components.infobox', ['col'=>'col-md-4 col-sm-6', 'icon'=>'list', 'isi'=>count($tipe),
    'judul'=>'Tipe', 'link'=>route('tipe.index')])
    {{-- @if (count($obat) == 0) --}}
    @include('components.infobox', ['col'=>'col-md-4 col-sm-6', 'icon'=>'clock', 'isi'=>count($obat),
    'judul'=>'Obat', 'link'=>count($obat) == 0 ? route('obat.create') : route('obat.index')])
    {{-- @endif --}}
</div>
<div class="row">
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-header">
                <h4>Daftar {{ucwords($title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('obat.create') }}" class="btn btn-primary">{{__('Tambah Data ')}} {{$title}} </a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="obat-table" class="table table-striped">
                        <thead>
                            <th>{{__('No')}}</th>
                            <th>{{__('Nama')}}</th>
                            <th>{{__('Tipe Obat')}}</th>
                            <th>{{__('Stok Obat')}}</th>
                            {{-- <th>{{__('Tanggal Expired')}}</th> --}}
                            <th>{{__('Aksi')}}</th>
                        </thead>
                        <tbody>
                            <?php $no=1 ?>
                            @foreach ($obat as $o)
                            <tr>
                                <td>{{$no}}</td>
                                <td>{{$o->name}}</td>
                                <td>{{$o->tipe->name}}</td>
                                <td>{{$o->stock}}</td>
                                <td>
                                    <a href="{{ route('obat.show', $o->id) }}" class="btn btn-sm btn-icon icon-left btn-info"><i class="far fa-info"></i> {{__('detail')}}</a>
                                    <a href="{{ route('obat.edit', $o->id) }}" class="btn btn-sm btn-icon icon-left btn-primary"><i class="far fa-edit"></i> {{__('Ubah')}}</a>
                                    <a href="{{ route('obat.destroy', $o->id) }}"
                                        class="btn btn-sm btn-danger hapus-obat" data-toggle="tooltip" data-placement="top"
                                        title="Hapus Data" data-id="{{ $o->id }}">
                                        <i class="fa fa-trash"></i> {{__('Hapus')}}
                                    </a>
                                </td>
                                <?php $no++ ?>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(document).ready(function() {
        $('#obat-table').DataTable();
    });

    $('.hapus-obat').on('click', function (e) {
        e.preventDefault();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var id = $(this).data("id");
        // var url = $('.hapus').attr('href');
        var url = "{{ route('obat.destroy', ":id") }}";
        url = url.replace(':id', id);
        $object=$(this);

        Swal.fire({
            title: 'Are you sure?',
            text: "Yakin ingin menghapus Data Obat ini!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    data: {id: id},
                    success: function (response) {
                        $($object).parents('tr').remove();
                        Swal.fire({
                            title: "Data Dihapus!",
                            text: response.message,
                            icon: 'success',
                        });
                        setTimeout(function () { 
                            location.reload();
                        }, 2500)
                    },
                    error: function (data) {
                        Swal.fire({
                            title: "Data Gagal Dihapus!",
                            icon: 'error',
                        })
                    }
                });
            }
        });
    })
</script>
@endpush
{{-- @include('import.chartjs') --}}
@include('import.datatable')
{{-- var ctx2 = document.getElementById("chartpermintaan").getContext('2d');
        var myChart = new Chart(ctx2, {
            type: 'bar',
            data: {
                labels: @json($label),
                datasets: [
                    @foreach ($chart as $c)
                    {
                        label: @json(ucfirst($c['kecamatan'])) ,
                        data: @json($c['permintaan']),
                        borderColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                        backgroundColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                        pointRadius: 4
                    },
                    @endforeach
                ]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: @json(ucfirst($title)),
                    }
                },
                legend: {
                    display: true
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    x: {
                        stacked: true,
                    },
                    y: {
                        stacked: true
                    }
                },
            },
        }); --}}

        {{-- $(document).ready(function() {
            var ctx1 = document.getElementById("chartharga").getContext('2d');
            var myChart = new Chart(ctx1, {
                type: 'bar',
                data: {
                    labels: @json($label),
                    datasets: [
                        @foreach ($chart as $c)
                        {
                            label: @json(ucfirst($c['kecamatan'])) ,
                            data: @json($c['harga']),
                            borderColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                            backgroundColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                            pointRadius: 4
                        },
                        @endforeach
                    ]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: @json(ucfirst($title)),
                        }
                    },
                    legend: {
                        display: true
                    },
                    interaction: {
                        intersect: false,
                        mode: 'index',
                    },
                    scales: {
                        x: {
                            stacked: true,
                        },
                        y: {
                            stacked: true
                        }
                    },
                },
            });
    
    
        }); --}}

resources/views/admin/medicine/show.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-header">
                <h4>Detail Data {{ucwords($title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('obat.index') }}" class="btn btn-primary">{{__('Kembali')}}</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="obat-table" class="table table-striped">
                        <thead>
                            <th>{{__('No')}}</th>
                            <th>{{__('Jumlah')}}</th>
                            <th>{{__('Status')}}</th>
                            <th>{{__('Tanggal Data')}}</th>
                            <th>{{__('Aksi')}}</th>
                        </thead>
                        <tbody>
                            <?php $no=1 ?>
                            @foreach ($data as $d)
                            <tr>
                                <td>{{$no}}</td>
                                <td>{{$d->quantity}}</td>
                                <td>{{$d->created_at->toDateString()}}</td>
                                <td>{{$d->status == 0 ? 'Habis' : 'Tersedia'}}</td>
                                <td>
                                    @if ($d->status != 0)
                                        <a href="{{ route('admin.obat.tambahStock', $d->id) }}" class="btn btn-sm btn-icon icon-left btn-success">
                                            <i class="far fa-plus"></i> 
                                            {{__('Tambah ke Stock obat')}}
                                        </a>
                                    @endif
                                    {{-- <a href="{{ route('obat.edit', $d->id) }}" class="btn btn-sm btn-icon icon-left btn-primary"><i class="far fa-edit"></i> {{__('Ubah')}}</a> --}}
                                    {{-- <a href="{{ route('obat.destroy', $d->id) }}"
                                        class="btn btn-sm btn-danger hapus-obat" data-toggle="tooltip" data-placement="top"
                                        title="Hapus Data" data-id="{{ $d->id }}">
                                        <i class="fa fa-trash"></i> {{__('Hapus')}}
                                    </a> --}}
                                </td>
                                <?php $no++ ?>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(document).ready(function() {
        $('#obat-table').DataTable();
    });

    // $('.hapus-obat').on('click', function (e) {
    //     e.preventDefault();

    //     $.ajaxSetup({
    //         headers: {
    //             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    //         }
    //     });

    //     var id = $(this).data("id");
    //     // var url = $('.hapus').attr('href');
    //     var url = "{{ route('obat.destroy', ":id") }}";
    //     url = url.replace(':id', id);
    //     $object=$(this);

    //     Swal.fire({
    //         title: 'Are you sure?',
    //         text: "Yakin ingin menghapus Data Obat ini!",
    //         icon: 'warning',
    //         showCancelButton: true,
    //         confirmButtonColor: '#3085d6',
    //         cancelButtonColor: '#d33',
    //         confirmButtonText: 'Ya!'
    //     }).then((result) => {
    //         if (result.value) {
    //             $.ajax({
    //                 url: url,
    //                 type: 'DELETE',
    //                 data: {id: id},
    //                 success: function (response) {
    //                     $($object).parents('tr').remove();
    //                     Swal.fire({
    //                         title: "Data Dihapus!",
    //                         text: response.message,
    //                         icon: 'success',
    //                     });
    //                     setTimeout(function () { 
    //                         location.reload();
    //                     }, 2500)
    //                 },
    //                 error: function (data) {
    //                     Swal.fire({
    //                         title: "Data Gagal Dihapus!",
    //                         icon: 'error',
    //                     })
    //                 }
    //             });
    //         }
    //     });
    // })
</script>
@endpush
@include('import.datatable')