routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DashboardController as adminDashboard;
use App\Http\Controllers\Admin\MedicineController as adminMed;
use App\Http\Controllers\Admin\MedicineTypeController as adminTypeMed;
use App\Http\Controllers\Admin\RecapController as adminRecapMed;
use App\Http\Controllers\Admin\IngoingController as adminObatMasuk;
use App\Http\Controllers\Admin\MedicineDataController as adminDataObat;
use App\Http\Controllers\Admin\OutgoingController as adminObatKeluar;
use App\Http\Controllers\Admin\ForecastingController as adminPeramalan;

use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => ['role:admin']], function () {
        //Dashboard
        Route::get('/dashboard', [adminDashboard::class, 'index'])->name('admin.dashboard');
        Route::post('ajax/getDataChart', [adminDashboard::class, 'getDataChart'])->name('admin.getDataChart');
        Route::get('ajax/getDataTahun', [adminDashboard::class, 'getDataTahun'])->name('admin.getTahun');
        Route::get('ajax/getDataObat', [adminDashboard::class, 'getDataObat'])->name('admin.getObat');
        Route::get('ajax/getDataLabel', [adminDashboard::class, 'getDataLabel'])->name('admin.getLabel');
        // Obat
        Route::resource('obat', adminMed::class);
        Route::get('obat/tambahStock/{id}', [adminMed::class, 'tambahStock'])->name('admin.obat.tambahStock');
        // Type
        Route::resource('tipe', adminTypeMed::class);
        // Recap
        Route::resource('rekap', adminRecapMed::class);
        Route::get('ajax/rekap/getTransaction', [adminRecapMed::class, 'getData'])->name('admin.rekap.getData');
        // Permintaan Transaction
        Route::resource('ingoing', adminObatMasuk::class);
        Route::resource('dataObat', adminDataObat::class);
        Route::get('ingoing/{id}/tipe', [adminObatMasuk::class, 'getType'])->name('ingoing.getType');
        // Obat Keluar Transaction
        Route::resource('outgoing', adminObatKeluar::class);
        Route::get('outgoing/{id}/tipe', [adminObatKeluar::class, 'getType'])->name('outgoing.getType');
        Route::get('ajax/outgoing/obat_all', [adminObatKeluar::class, 'getObat'])->name('outgoing.getObat');
        Route::get('ajax/outgoing/keranjang_all', [adminObatKeluar::class, 'getKeranjang'])->name('outgoing.getKeranjang');
        Route::get('ajax/outgoing/detail/{id}', [adminObatKeluar::class, 'getDetailTransaction'])->name('outgoing.getDetailInfo');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/addCart', [adminObatKeluar::class, 'addCart'])->name('outgoing.addCart');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/deleteItem', [adminObatKeluar::class, 'deleteItem'])->name('outgoing.deleteCartItem');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/updateItem', [adminObatKeluar::class, 'updateItem'])->name('outgoing.updateCartItem');
        // Forecasting
        Route::get('/forecasting', [adminPeramalan::class, 'index'])->name('admin.forecasting');
        Route::get('ajax/forecasting/getDataTahun/', [adminPeramalan::class, 'getDataTahun'])->name('admin.forecasting.getDataTahun');
        Route::get('ajax/forecasting/getDataBulan/', [adminPeramalan::class, 'getDataBulan'])->name('admin.forecasting.getDataBulan');
        Route::get('ajax/forecasting/getDataObat/', [adminPeramalan::class, 'getDataObat'])->name('admin.forecasting.getDataObat');
        Route::post('ajax/forecasting/calcultaeForecasting/', [adminPeramalan::class, 'calcultaeForecasting'])->name('admin.forecasting.calculateForecasting');
    });
});

Route::get('/landing', [HomeController::class, 'index'])->name('landing');

app/Http/Controllers/Admin/IngoingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Medicine;
use App\Models\MedicineDetail;
use App\Models\MedicineType;
use App\Models\Transaction;
use App\Models\TransactionDetail;
use App\Models\TransactionStatus;
use Carbon\Carbon;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class IngoingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permintaan = Transaction::where('deleted_at', null)
            ->whereNotIn('status_id', [5])
            ->whereIn('type_id', [1])
            ->with(['status_transaksi','detail_transaksi'])->get();
            
        return view('admin.ingoing.index', [
            'title' => 'ingoing',
            'subtitle' => '',
            'active' => 'permintaan',
            'order' => $permintaan,
            // 'obat' => $obat
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $obat = Medicine::all();
        return view('admin.ingoing.create', [
            'title' => 'ingoing',
            'subtitle' => 'create',
            'active' => 'permintaan',
            'obat' => $obat
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'obat' => 'required',
            'jumlah' => 'required|numeric',
            'expired_date' => 'required|date'
        ], [
            'obat.required' => 'Obat harap diisi',
            'jumlah.required' => 'Tipe harus diisi',
            'jumlah.numeric' => 'satuan miligram harus angka',
            'expired_date.required' => 'tanggal expired harus diisi',
            'expired_date.date' => 'tanggal expired harus format tanggal',
        ]);

        $date = new DateTime($request->expired_date);
        $invoice = $this->generateInvoice(); 
        $user = Auth::user();
        $order = Transaction::create([
            'invoice_number' => $invoice,
            'status_id' => 2,
            'type_id' => 1,
            'created_by' => $user->id
        ]);

        TransactionDetail::insert([
            'transaction_id' => $order->id,
            'medicine_id' => $request->obat,
            'price' => '0',
            'quantity' => $request->jumlah,
            'expired_date' => $date->format('Y-m-d H:i:s'),
        ]);

        return redirect()->route('ingoing.index')->with('success_msg', 'Tambah Obat Masuk berhasil ditambah dengan status dikirim');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $detail = TransactionDetail::where('transaction_id', $id)->with('transaksi', 'obat')->first();
        $data = TransactionDetail::where('transaction_id', $id)->with('transaksi', 'obat')->get();
        // dd($data);

        return view('admin.ingoing.show', [
            'title' => 'ingoing',
            'subtitle' => 'show',
            'active' => 'permintaan',
            'detail' => $detail,
            'data' => $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pesan = '';
        $data = Transaction::findOrFail($id);
        $coba  = '';
        if ($data != null) {
            if ($data->status_id == 1) {
                Transaction::where('id', $id)
                    ->update([
                        'status_id' => 2
                    ]);
                $pesan = 'Status Data Order berhasil diupdate';
            } elseif ($data->status_id == 2) {
                Transaction::where('id', $id)
                    ->update([
                        'status_id' => 3
                    ]);
                $pesan = 'Status Data Order berhasil diupdate';
            }  elseif ($data->status_id == 3) {
                Transaction::where('id', $id)
                    ->update([
                        'status_id' => 4
                    ]);
                $coba = MedicineDetail::insert([
                    'medicine_id' => $data->detail_transaksi[0]->medicine_id,
                    'quantity' => $data->detail_transaksi[0]->quantity,
                    'expired_date' => $data->detail_transaksi[0]->expired_date,
                    'status' => '1',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s')
                ]);
                $pesan = 'Status Data Order berhasil diupdate';
            }
            $coba = $coba;
        } else {
            $pesan = 'Data Order tidak ditemukan';
        }
        
        return response()->json([
            'message' => $pesan,
            'coba' => $coba
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $status = TransactionStatus::where('name', 'batal')->first();
        Transaction::where('id', $id)
            ->update([
                'status_id' => $status->id
            ]);
        $target = Transaction::where('id', $id);
        $target->delete();
        return response()->json([
            'message' => 'Data Order berhasil dihapus!'
        ]);
    }

    public function getType($id)
    {
        return MedicineType::where('id', $id)->get();
    }

    private function generateInvoice()
    {
        $date   = new DateTime();

        $result = $date->format('Y-m-d-H-i-s');
        $krr    = explode('-', $result);
        $finv   = implode("", $krr);
        
        $digits = 3;
        $ra = rand(pow(10, $digits-1), pow(10, $digits)-1);
        $res = 'INV'.$ra.$finv;

        return $res;
    }
}

resources/views/admin/ingoing/create.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>{{ucfirst($title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('ingoing.index') }}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('ingoing.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>{{__('Obat')}}</label>
                        <select name="obat" id="obat" class="form-control @error('obat') is-invalid @enderror">
                            <option value=""></option>
                            @foreach ($obat as $o)
                                <option value="{{$o->id}}">{{$o->tipe->name}} {{$o->name}}</option>
                            @endforeach
                        </select>
                        @error('obat')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>{{__('Jumlah')}}</label>
                        <div class="input-group">
                            <input name="jumlah" type="text" class="form-control @error('jumlah') is-invalid @enderror"
                                value="{{ old('jumlah') }}" autocomplete="jumlah" autofocus>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <label for="type" id="type">Tipe Obat</label>
                                </div>
                            </div>
                            @error('jumlah')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group">
                        <label>{{__('Expired Date')}}</label>
                        <input name="expired_date" type="text" id="exp-date" class="form-control @error('expired_date') is-invalid @enderror"
                            value="{{ old('expired_date') }}" autocomplete="expired_date" data-date-format='dd-mm-yyyy' autofocus>
                        @error('expired_date')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <input type="submit" class="btn btn-primary float-right" value="Tambah">
                </form>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    var dateToday = new Date();
    $(document).ready(function(){
        $("#exp-date").datepicker({
            autoclose: true,
            startDate: dateToday,
            onSelect: function(selectedDate) {
                $('#exp-date').text();
            }
        });
        $("#obat").select2({
            placeholder: "Pilih Tipe Obat",
            allowClear: true
        });
        $('#obat').change(function() {
            var target = $(this).val();

            var url = '{{ route("ingoing.getType", ':obat') }}';
            url = url.replace(':obat', target);
            // console.log(url, target)
            $.get(url, function(data) {
                var select = $('#type');
                select.empty();
                $.each(data,function(key, value) {
                    select.append(value.name);
                });
            });
        });
    })
</script>
@endpush
@endsection

@include('import.select2')
@include('import.datepicker')

resources/views/admin/ingoing/create1.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>{{__('Tambah Data Obat')}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('ingoing.index') }}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('dataObat.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>{{__('Obat')}}</label>
                        <select name="obat" id="obat" class="form-control @error('obat') is-invalid @enderror">
                            <option value=""></option>
                            @foreach ($obat as $o)
                                <option value="{{$o->id}}">{{$o->tipe->name}} {{$o->name}}</option>
                            @endforeach
                        </select>
                        @error('obat')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>{{__('Jumlah')}}</label>
                        <input name="jumlah" type="text" class="form-control @error('jumlah') is-invalid @enderror"
                                value="{{ old('jumlah') }}" autocomplete="jumlah" autofocus>
                        @error('jumlah')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>{{__('Bulan')}}</label>
                                <input name="bulan" type="text" id="month" class="form-control @error('bulan') is-invalid @enderror"
                                    value="{{ old('bulan') }}" autocomplete="bulan" data-date-format='mm' autofocus>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>{{__('Tahun')}}</label>
                                <input name="tahun" type="text" id="year" class="form-control @error('tahun') is-invalid @enderror"
                                    value="{{ old('tahun') }}" autocomplete="tahun" data-date-format='yyyy' autofocus>
                            </div>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary float-right" value="Tambah">
                </form>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    var dateToday = new Date();
    $(document).ready(function(){
        $("#exp-date").datepicker({
            autoclose: true,
            startDate: dateToday,
            onSelect: function(selectedDate) {
                $('#exp-date').text();
            }
        });
        $("#obat").select2({
            placeholder: "Pilih Tipe Obat",
            allowClear: true
        });
        $('#obat').change(function() {
            var target = $(this).val();

            var url = '{{ route("ingoing.getType", ':obat') }}';
            url = url.replace(':obat', target);
            $.get(url, function(data) {
                var select = $('#type');
                select.empty();
                $.each(data,function(key, value) {
                    select.append(value.name);
                });
            });
        });
        $("#month").datepicker({
            format: "mm",
            viewMode: "months", 
            minViewMode: "months",
            autoclose: true,
            onSelect: function(selectedDate) {
                $('#month').text();
            }
        });
        $("#year").datepicker({
            format: "yyyy",
            viewMode: "years", 
            minViewMode: "years",
            autoclose: true,
            onSelect: function(selectedDate) {
                $('#year').text();
            }
        });
    })
</script>
@endpush
@endsection

@include('import.select2')
@include('import.datepicker')

resources/views/admin/ingoing/index.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-header">
                <h4>Daftar {{ucwords($title == 'ingoing' ? 'Obat Masuk' : $title)}}</h4>
                <div class="card-header-action">
                    <a href="{{ route('ingoing.create') }}" class="btn btn-primary">{{__('Tambah ')}} {{$title == 'ingoing' ? 'Obat Masuk' : $title}} </a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="obat-table" class="table table-striped">
                        <thead>
                            <th>{{__('No')}}</th>
                            <th>{{__('Nomor Invoice')}}</th>
                            <th>{{__('Status')}}</th>
                            <th>{{__('Tanggal Dibuat')}}</th>
                            <th>{{__('Aksi')}}</th>
                            {{-- <th>{{__('Aksi')}}</th> --}}
                        </thead>
                        <tbody>
                            <?php $no=1 ?>
                            @foreach ($order as $o)
                            <tr>
                                <td>{{$no}}</td>
                                <td>{{$o->invoice_number}}</td>
                                <td>{{$o->status_transaksi->name}}</td>
                                <td>{{$o->created_at == null ? '-' : $o->created_at}}</td>
                                <td>
                                    @if ($o->status_id != 4)
                                    <a href="{{ route('ingoing.edit', $o->id) }}" 
                                        class="btn btn-sm btn-icon icon-left btn-primary update-status-obat" 
                                        data-id="{{ $o->id }}">
                                        <i class="far fa-edit"></i> 
                                        @if ($o->status_id == 1)
                                        {{__('Bayar')}}
                                        @elseif ($o->status_id == 2)
                                        {{__('Kirim')}}
                                        @elseif ($o->status_id == 3)
                                        {{__('Selesai')}}
                                        @endif
                                    </a>
                                    <a href="{{ route('ingoing.destroy', $o->id) }}"
                                        class="btn btn-sm btn-danger hapus-obat" data-toggle="tooltip" data-placement="top"
                                        title="Hapus Data" data-id="{{ $o->id }}">
                                        <i class="fa fa-trash"></i> Batal
                                    </a>
                                    @endif
                                    <a href="{{ route('ingoing.show', $o->id) }}" class="btn btn-sm btn-icon icon-left btn-info" ><i class="far fa-info"></i> {{__('Detail')}}</a>
                                </td>
                                <?php $no++ ?>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(document).ready(function() {
        $('#obat-table').DataTable();
    });

    $('.hapus-obat').on('click', function (e) {
        e.preventDefault();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var id = $(this).data("id");
        // var url = $('.hapus').attr('href');
        var url = "{{ route('ingoing.destroy', ":id") }}";
        url = url.replace(':id', id);
        $object=$(this);

        Swal.fire({
            title: 'Are you sure?',
            text: "Yakin ingin menghapus Data Obat ini!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    data: {id: id},
                    success: function (response) {
                        $($object).parents('tr').remove();
                        Swal.fire({
                            title: "Data Dihapus!",
                            text: response.message,
                            icon: 'success',
                        });
                        reloadPage(2000);
                    },
                    error: function (data) {
                        console.log(data);
                        Swal.fire({
                            title: "Data Gagal Dihapus!",
                            icon: 'error',
                        })
                    }
                });
            }
        });
    })

    $('.update-status-obat').on('click', function (e) {
        e.preventDefault();
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var id = $(this).data("id");
        var url = "{{ route('ingoing.update', ":id") }}";
        url = url.replace(':id', id);
        $object=$(this);

        console.log(url, id);

        Swal.fire({
            title: 'Are you sure?',
            text: "Yakin Ubah status Data Order ini!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: 'PUT',
                    data: {id: id, '_method':'PUT'},
                    success: function (response) {
                        // $($object).parents('tr').remove();
                        Swal.fire({
                            title: "Data Diupdate!",
                            text: response.message,
                            icon: 'success',
                        });
                        reloadPage(2500);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(jqXHR, textStatus, errorThrown);
                        Swal.fire({
                            title: "Data Gagal Diupdate!",
                            icon: 'error',
                        })
                    }
                });
            }
        });
    })

    function reloadPage(counter) {
        setTimeout(function () { 
            location.reload();
        }, counter)
    }
</script>
@endpush
@include('import.datatable')

resources/views/admin/ingoing/show.blade.php
@extends('layouts.myview')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>{{__('Order Status')}}</h4>
            </div>
            <div class="card-body">
                <div class="row mt-4">
                    <div class="col-12 col-lg-8 offset-lg-2">
                        <div class="wizard-steps">
                            @if ($detail->transaksi->status_id == 1)
                                @include('components.wizard.placed')
                            @elseif ($detail->transaksi->status_id == 2)
                                @include('components.wizard.placed')
                                @include('components.wizard.payment')
                            @elseif ($detail->transaksi->status_id == 3)
                                @include('components.wizard.placed')
                                @include('components.wizard.payment')
                                @include('components.wizard.shipped')
                            @elseif ($detail->transaksi->status_id == 4)
                                @include('components.wizard.placed')
                                @include('components.wizard.payment')
                                @include('components.wizard.shipped')
                                @include('components.wizard.status.complete')
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-header">
                <h4>Detail Data {{$detail->transaksi->invoice_number}}</h4>
                <div class="card-header-action">
                    {{-- <a href="{{ route('order.create') }}" class="btn btn-primary">{{__('Tambah Data ')}} {{$title}} </a> --}}
                </div>
            </div>
            <div class="card-body">
                <table id="obat-table" class="table table-striped">
                    <thead>
                        <th>{{__('No')}}</th>
                        <th>{{__('Nama Obat')}}</th>
                        <th>{{__('Harga')}}</th>
                        <th>{{__('Kuantitas')}}</th>
                        <th>{{__('Tanggal Kadaluarsa')}}</th>
                    </thead>
                    <tbody>
                        <?php $no=1 ?>
                        @foreach ($data as $d)
                        <tr>
                            <td>{{$no}}</td>
                            <td>{{$d->obat->name}}</td>
                            {{-- <td></td> --}}
                            <td>{{$d->price}}</td>
                            <td>{{$d->quantity}}</td>
                            <td>{{$d->expired_date}}</td>
                            <?php $no++ ?>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{-- @php
                    dd($detail)
                @endphp --}}
            </div>

        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>

</script>
@endpush