routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DashboardController as adminDashboard;
use App\Http\Controllers\Admin\MedicineController as adminMed;
use App\Http\Controllers\Admin\MedicineTypeController as adminTypeMed;
use App\Http\Controllers\Admin\RecapController as adminRecapMed;
use App\Http\Controllers\Admin\IngoingController as adminObatMasuk;
use App\Http\Controllers\Admin\MedicineDataController as adminDataObat;
use App\Http\Controllers\Admin\OutgoingController as adminObatKeluar;
use App\Http\Controllers\Admin\ForecastingController as adminPeramalan;

use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => ['role:admin']], function () {
        //Dashboard
        Route::get('/dashboard', [adminDashboard::class, 'index'])->name('admin.dashboard');
        Route::post('ajax/getDataChart', [adminDashboard::class, 'getDataChart'])->name('admin.getDataChart');
        Route::get('ajax/getDataTahun', [adminDashboard::class, 'getDataTahun'])->name('admin.getTahun');
        Route::get('ajax/getDataObat', [adminDashboard::class, 'getDataObat'])->name('admin.getObat');
        Route::get('ajax/getDataLabel', [adminDashboard::class, 'getDataLabel'])->name('admin.getLabel');
        // Obat
        Route::resource('obat', adminMed::class);
        Route::get('obat/tambahStock/{id}', [adminMed::class, 'tambahStock'])->name('admin.obat.tambahStock');
        // Type
        Route::resource('tipe', adminTypeMed::class);
        // Recap
        Route::resource('rekap', adminRecapMed::class);
        Route::get('ajax/rekap/getTransaction', [adminRecapMed::class, 'getData'])->name('admin.rekap.getData');
        // Permintaan Transaction
        Route::resource('ingoing', adminObatMasuk::class);
        Route::resource('dataObat', adminDataObat::class);
        Route::get('ingoing/{id}/tipe', [adminObatMasuk::class, 'getType'])->name('ingoing.getType');
        // Obat Keluar Transaction
        Route::resource('outgoing', adminObatKeluar::class);
        Route::get('outgoing/{id}/tipe', [adminObatKeluar::class, 'getType'])->name('outgoing.getType');
        Route::get('ajax/outgoing/obat_all', [adminObatKeluar::class, 'getObat'])->name('outgoing.getObat');
        Route::get('ajax/outgoing/keranjang_all', [adminObatKeluar::class, 'getKeranjang'])->name('outgoing.getKeranjang');
        Route::get('ajax/outgoing/detail/{id}', [adminObatKeluar::class, 'getDetailTransaction'])->name('outgoing.getDetailInfo');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/addCart', [adminObatKeluar::class, 'addCart'])->name('outgoing.addCart');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/deleteItem', [adminObatKeluar::class, 'deleteItem'])->name('outgoing.deleteCartItem');
        Route::post('ajax/outgoing/{transaction}/obat/{medicine}/updateItem', [adminObatKeluar::class, 'updateItem'])->name('outgoing.updateCartItem');
        // Forecasting
        Route::get('/forecasting', [adminPeramalan::class, 'index'])->name('admin.forecasting');
        Route::get('ajax/forecasting/getDataTahun/', [adminPeramalan::class, 'getDataTahun'])->name('admin.forecasting.getDataTahun');
        Route::get('ajax/forecasting/getDataBulan/', [adminPeramalan::class, 'getDataBulan'])->name('admin.forecasting.getDataBulan');
        Route::get('ajax/forecasting/getDataObat/', [adminPeramalan::class, 'getDataObat'])->name('admin.forecasting.getDataObat');
        Route::post('ajax/forecasting/calcultaeForecasting/', [adminPeramalan::class, 'calcultaeForecasting'])->name('admin.forecasting.calculateForecasting');
    });
});

Route::get('/landing', [HomeController::class, 'index'])->name('landing');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
        <title>SIPPO</title>

        <!-- General CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
            integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

        <!-- CSS Libraries -->
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap-social/bootstrap-social.css') }}">

        <!-- Template CSS -->
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
    </head>

    <body>
        <div id="app">
            <section class="section">
                <div class="container mt-5">
                    <div class="row">
                        @yield('content')
                    </div>
                </div>
            </section>
        </div>

        <!-- General JS Scripts -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
        <script src="{{ asset('assets/js/stisla.js') }}"></script>

        <!-- JS Libraies -->

        <!-- Template JS File -->
        <script src="{{ asset('assets/js/scripts.js') }}"></script>
        <script src="{{ asset('assets/js/custom.js') }}"></script>

        <!-- Page Specific JS File -->
    </body>

</html>

resources/views/layouts/error_msg.blade.php
@if(session('error_msg'))
<div class="alert alert-danger alert-dismissible show fade">
    <button class="close" data-dismiss="alert">
        <span>&times;</span>
    </button>
    {{ session('error_msg') }}
</div>
@endif

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    {{-- <div class="footer-left">
        Copyright &copy; 2018 <div class="bullet"></div> --}}
        {{-- Design By <a href="https://nauval.in/">Muhamad
            Nauval Azhar</a> --}}
    {{-- </div> --}}
    {{-- <div class="footer-right">
        2.3.0
    </div> --}}
</footer>

resources/views/layouts/header.blade.php
<div class="section-header">
    <h1>
        @if ($title == 'outgoing')
        {{__('Obat Keluar')}}    
        @elseif ($title == 'ingoing')
        {{__('Obat Masuk')}}
        @elseif ($title == 'rekap')
        {{__('Rekap Data Transaksi Obat')}}
        @else
        {{ucfirst($title)}}
        @endif
    </h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">SIPPO</a></div>
        {{-- @if (auth()->user()->role_id == 1)
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">SIMPELAN</a></div>
        @else
        <div class="breadcrumb-item"><a href="{{ route('holtikultura.dashboard') }}">SIMPELAN</a></div>
        @endif --}}
        @if ($subtitle == null)
        <div class="breadcrumb-item active">
            <a href="{{ route('admin.dashboard') }}">{{ $title }}</a>
        </div>
        @else
        @if ($title == 'dashboard')
        <div class="breadcrumb-item"><a href="#">{{ucfirst($title)}}</a></div>
        @else
        <div class="breadcrumb-item"><a href="{{ route($title.'.index', $id ?? '') }}">{{ucfirst($title)}}</a></div>
        @endif
        <div class="breadcrumb-item active">{{ucfirst($subtitle)}}</div>
        @endif
    </div>
</div>

resources/views/layouts/landing.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
        <title>SIMPELAN</title>

        <!-- General CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
            integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

        <!-- CSS Libraries -->

        <!-- Template CSS -->
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">

        @stack('css')
        @stack('styles')

    </head>

    <body class="layout-3">
        <div id="app">
            <div class="main-wrapper container">
                <div class="navbar-bg"></div>
                <nav class="navbar navbar-expand-lg main-navbar">
                    <a href="{{ route('landing') }}" class="navbar-brand sidebar-gone-hide">SIMPELAN</a>
                    <div class="navbar-nav">
                        <a href="#" class="nav-link sidebar-gone-show" data-toggle="sidebar"><i
                                class="fas fa-bars"></i></a>
                    </div>
                    {{-- <div class="nav-collapse">
                        <a class="sidebar-gone-show nav-collapse-toggle nav-link" href="#">
                            <i class="fas fa-ellipsis-v"></i>
                        </a>
                        <ul class="navbar-nav">
                            <li class="nav-item active"><a href="#" class="nav-link">Application</a></li>
                            <li class="nav-item"><a href="#" class="nav-link">Report Something</a></li>
                            <li class="nav-item"><a href="#" class="nav-link">Server Status</a></li>
                        </ul>
                    </div> --}}
                </nav>

                <!-- Main Content -->
                <div class="main-content">
                    <section class="section">
                        <div class="section-body">
                            @yield('content')
                        </div>
                    </section>
                </div>
                @include('layouts.footer')
            </div>
        </div>

        <!-- General JS Scripts -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
        <script src="{{ asset('assets/js/stisla.js') }}"></script>

        <!-- JS Libraies -->

        <!-- Page Specific JS File -->

        <!-- Template JS File -->
        <script src="{{ asset('assets/js/scripts.js') }}"></script>
        <script src="{{ asset('assets/js/custom.js') }}"></script>

        @stack('js')
        @stack('scripts')

    </body>

</html>

resources/views/layouts/myview.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>SIPPO</title>

        <!-- General CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
            integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

        <link rel="stylesheet" href="{{ asset('vendor/izitoast/dist/css/iziToast.min.css') }}">
        <!-- Template CSS -->
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">

        @stack('css')
        @stack('styles')

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script>
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        </script>
    </head>

    <body>
        <div id="app">
            <div class="main-wrapper">
                <div class="navbar-bg"></div>
                @include('layouts.navbar')
                @include('layouts.sidebar')

                <!-- Main Content -->
                <div class="main-content">
                    <section class="section">
                        @include('layouts.header')
                        @include('layouts.error_msg')
                        @include('layouts.success_msg')
                        @yield('content')
                    </section>
                    @yield('modal')
                </div>
                @include('layouts.footer')
            </div>
        </div>

        <!-- General JS Scripts -->
        {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script> --}}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

        <script src="{{ asset('assets/js/stisla.js') }}"></script>
        @stack('js')
        <script src="{{ asset('vendor/izitoast/dist/js/iziToast.min.js') }}"></script>

        <!-- Template JS File -->
        <script src="{{ asset('assets/js/scripts.js') }}"></script>
        <script src="{{ asset('assets/js/custom.js') }}"></script>

        @stack('scripts')

    </body>

</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                        class="fas fa-search"></i></a></li>
        </ul>
        <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
            <div class="search-backdrop"></div>
            <div class="search-result">
            </div>
        </div>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
                {{-- {{ auth()->user()->role_id == 1 ? auth()->user()->mantri->avatar : auth()->user()->holtikultura->avatar }} --}}
                <div class="d-sm-none d-lg-inline-block">
                    {{-- {{ auth()->user()->role_id == 1 ? auth()->user()->mantri->nama_depan : auth()->user()->holtikultura->nama_depan }} --}}
                    {{ auth()->user()->username }}
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                {{-- <div class="dropdown-title">Logged in 5 min ago</div> --}}
                {{-- @if (auth()->user()->role_id ==2)
                <a href="{{ route('profil.index') }}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> {{__('Profil')}}
                </a>
                @endif --}}

                {{-- <a href="{{ auth()->user()->role_id == 1 ? route('admin.index') : route('holtikultura.index') }}" class="dropdown-item has-icon">
                    <i class="fas fa-cog"></i> Settings
                </a> --}}
                <div class="dropdown-divider"></div>
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="#">{{__("SIPPO")}}</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="#">{{__("SPO")}}</a>
        </div>
        <ul class="sidebar-menu">
            <li class="{{ $active == 'dashboard' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.dashboard') }}">
                    <i class="far fa-home"></i>
                    <span>{{__('Dashboard')}}</span>
                </a>
            </li>
            <li class="menu-header">{{__("Menu")}}</li>
            @if (auth()->user()->role_id == 1)
            {{-- <li class="nav-item dropdown {{ $active == 'produksi' || $active == 'permintaan' ? 'active' : '' }}">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-seedling"></i><span>Buah Naga</span></a>
                <ul class="dropdown-menu">
                    <li class="{{ $active == 'produksi' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('produksi.index') }}">{{__('Produksi')}}</a>
                    </li>
                    <li class="{{ $active == 'permintaan' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('permintaan.index') }}">{{__('Permintaan')}}</a>
                    </li>
                </ul>
            </li> --}}
            <li class="{{ $active == 'obat' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('obat.index') }}">
                    <i class="far fa-pills"></i>
                    <span>{{__('Obat')}}</span>
                </a>
            </li>
            <li class="menu-header">{{__("Transaksi")}}</li>
            {{-- <li class="{{ $active == 'order' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('order.index') }}">
                    <i class="far fa-tag"></i>
                    <span>{{__('Stok Obat')}}</span>
                </a>
            </li> --}}
            <li class="nav-item dropdown {{ $active == 'outgoing' || $active == 'permintaan' ? 'active' : '' }}">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-tag"></i><span>{{__('Stok Obat')}}</span></a>
                <ul class="dropdown-menu">
                    <li class="{{ $active == 'permintaan' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('ingoing.index') }}">{{__('Obat Masuk')}}</a>
                    </li>
                    <li class="{{ $active == 'outgoing' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('outgoing.index') }}">{{__('Obat Keluar')}}</a>
                    </li>
                </ul>
            </li>
            <li class="{{ $active == 'peramalan' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.forecasting') }}">
                    {{-- {{ route('order.index') }} --}}
                    <i class="far fa-bullseye"></i>
                    <span>{{__('Peramalan')}}</span>
                </a>
            </li>
            <li class="{{ $active == 'rekap' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('rekap.index') }}">
                    {{-- {{ route('order.index') }} --}}
                    <i class="far fa-seedling"></i>
                    <span>{{__('Rekap Data')}}</span>
                </a>
            </li>
            {{-- <li class="nav-item dropdown {{ $active == '' || $active == 'permintaan' ? '' : '' }}">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-seedling"></i><span>{{__('Rekap Data')}}</span></a>
                <ul class="dropdown-menu">
                    <li class="{{ $active == '' ? 'active' : '' }}">
                        <a class="nav-link" href="#">{{__('Masuk')}}</a>
                    </li>
                    <li class="{{ $active == 'permintaan' ? 'active' : '' }}">
                        <a class="nav-link" href="#">{{__('Keluar')}}</a>
                    </li>
                </ul>
            </li> --}}
            {{-- <li class="nav-item dropdown {{ $active == 'forePro' || $active == 'forePer' ? 'active' : '' }}">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Peramalan</span></a>
                <ul class="dropdown-menu">
                    <li class="{{ $active == 'forePro' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('forecast.produksi.index') }}">Produksi</a>
                    </li>
                    <li class="{{ $active == 'forePer' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('forecast.permintaan.index') }}">Permintaan</a>
                    </li>
                </ul>
            </li>
            <li class="menu-header">{{__("Pengaturan")}}</li>
            <li class="nav-item dropdown {{ $active == 'profil' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('mantri.index') }}">
                    <i class="far fa-cogs"></i>
                    <span>{{__('Profil')}}</span>
                </a>
            </li> --}}
            @endif
        </ul>
    </aside>
</div>

resources/views/layouts/success_msg.blade.php
@if(session('success_msg'))
<div class="alert alert-success alert-dismissible show fade">
    <button class="close" data-dismiss="alert">
        <span>&times;</span>
    </button>
    {{ session('success_msg') }}
</div>
@endif